### ISSUE TITLE
dont extrac my log

### ISSUE THREAD

**Issue by EtemadReza** [barakat-abweh/TA-pfsense#6]
hi
i install it on my search head and indexer bet it dont work. can you help me

**Comment by barakat-abweh** [comment]
Could you please add more details to the case:
For example the log format and the sourcetype you configured

**Comment by EtemadReza** [comment]
Thank you for your responding
1) I copy file to opt/splunk/etc/apps  on both search head and indexer

2) change inputs.conf and indexes.conf
[udp://5014]
index = firewall_srv
sourcetype = pfsense
connection_host = IP
no_appending_timestamp = true
disabled = 0

[firewall_srv]
coldPath = $SPLUNK_DB/firewall_srv/colddb
homePath = $SPLUNK_DB/firewall_srv/db
thawedPath = $SPLUNK_DB/firewall_srv/thaweddb

data inpout 
![image](https://github.com/user-attachments/assets/f2d64728-eaa0-467d-b696-9cc9ed7f4ac9)

search result
![image](https://github.com/user-attachments/assets/90c580d3-f86b-40dd-b09b-0b633a841ea3)

**Comment by barakat-abweh** [comment]
Could you please show the log format from pfsense and the version

**Comment by EtemadReza** [comment]
![image](https://github.com/user-attachments/assets/3a33d641-8dbc-4150-b03d-21b4e9c9b8c2)

![image](https://github.com/user-attachments/assets/623bb807-ff07-4463-84a6-cd12f8d3338d)

![image](https://github.com/user-attachments/assets/8872a4ae-5e09-4158-a90c-e4e750a6c2a1)

**Comment by barakat-abweh** [comment]
Please change it to syslog format and check

If this doesn't work I can join a meeting to help troubleshoot the issue

**Comment by EtemadReza** [comment]
thank you
it was my fault.
You said change log format
your app and your support are amazing

**Comment by EtemadReza** [comment]
thank you
it was my fault.
You said change log format
your app and your support are amazing

**Comment by barakat-abweh** [comment]
You're welcome.

It's not your fault, I'll make sure this point is clear in the readme file.

If anything changes just contact.
