### ISSUE TITLE
Add-on Installation Failed

### ISSUE THREAD

**Issue by jhill-cmd** [barakat-abweh/TA-pfsense#8]
Using the UI "Browse More Apps"

<img width="583" alt="Screenshot 2024-08-27 at 09 23 43" src="https://github.com/user-attachments/assets/e2c8c907-750d-4704-92c4-5eb5f5ad54e1">

**Comment by barakat-abweh** [comment]
Could you please provide more details so we at least can dig to find the reason?

Try to install it using the command line and provide the output

Or decompress the zip file and copy it directly to the app folder and provide your notes

Thanks

**Comment by jhill-cmd** [comment]
Interesting through command line it worked perfectly. 
While through the splunk UI, based on the "Browse More Apps" store, it fails with the pop up.

**Comment by barakat-abweh** [comment]
Did the suggestion solve your issue?

Can we close this issue?
