### ISSUE TITLE
Possible issue with Regex in transforms.conf

### ISSUE THREAD

**Issue by rayperkins1** [barakat-abweh/TA-pfsense#9]
Thanks for doing all this work!  I was able to install this app in splunk, but the transform for source type was not working, everything was sourcetype=pfsense.

I took sample logs and your regex to regex101.com and found that a minor edit made everything work.  There is a literal + (\+) that I replaced with a dash (-) and that seemed to make everything work.

Original
```
#REGEX = \d+\s+\d+\-\d+\-\d+\S+\d+:\d+:\d+\.\d+\+\d+:\d+\s+\S+\.\S+\.\S+\s+(?P<sourcetype>\S+)\s+.*
```
Update:
```
 REGEX = \d+\s+\d+\-\d+\-\d+\S+\d+:\d+:\d+\.\d+-\d+:\d+\s+\S+\.\S+\.\S+\s+(?P<sourcetype>\S+)\s+.*
```

**Comment by whocancatchme** [comment]
Yes. that is correct. Once, I replaced old regex with above one, then it started working.

**Comment by barakat-abweh** [comment]
Hi, it seems that this typo had a huge effect on the transform.

Thanks for your efforts, I'll update the type to the suggested one or what I prefer is the you @rayperkins1 make a merge request so your effort can be recognized.

Thanks

**Comment by barakat-abweh** [comment]
Just fixed the typo, thank you
